package com.shootinggame;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;

import javax.swing.ImageIcon;

import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

@SuppressWarnings("serial")
public class ShootingGame extends javax.swing.JFrame 
{
	// JLabel jLabe2=new JLabel();
	// Dimension
	// For Width
	int wth[] = { 10, 130, 260, 390, 530, 660, 790, 930 };
	// For Height
	int hth[] = { 10, 145, 280, 415, 510 };
	int w;
	int h;
	Thread th;

	public ShootingGame() 
	{
		initComponents();

		Toolkit t = Toolkit.getDefaultToolkit();
		Dimension d = t.getScreenSize();
		setSize(1155, 650);
		int sw = (int) d.getWidth();
		int sh = (int) d.getHeight();

		setLocation((sw - 1155) / 2, (sh - 650) / 2);

		th = new Thread(new Runnable() {
			@Override
			public void run() {

				// jPanel1.add(jLabe2);
				while (true) {
					ImageIcon icon = new ImageIcon("src/image/animatedghost.gif");

					jLabe2.setIcon(icon);
					w = (int) (Math.random() * 8);
					h = (int) (Math.random() * 5);
					jLabe2.setBounds(wth[w], hth[h], 118, 132);
					try {
						Thread.sleep(1800);
					} catch (InterruptedException ex) {
					}

				}

			}
		});
		th.start();

		Image img = t.getImage("src/image/target.png");
		Cursor cr = t.createCustomCursor(img, new Point(0, 0), "imgs");
		jLabe2.setCursor(cr);
		jLabe2.addMouseListener(new MyListener());

	}

	static int coun = 1;

	public class MyListener implements MouseListener {

		@Override
		public void mouseClicked(MouseEvent e) {

			System.out.println("Rishabh");
			try {

				final URL resource = getClass().getResource("src/image/Winchester.mp3");
				final Media media = new Media(resource.toString());
				final MediaPlayer mediaPlayer = new MediaPlayer(media);
				mediaPlayer.play();

			} catch (Exception ex) {
			}

			jLabel1.setText("Score: " + coun);
			ImageIcon icon = new ImageIcon("src/image/explosion1234.gif");

			jLabe2.setIcon(icon);

			jLabe2.setBounds(wth[w], hth[h], 118, 132);
			coun++;

		}

		@Override
		public void mousePressed(MouseEvent e) {
			// throw new UnsupportedOperationException("Not supported yet."); //To change
			// body of generated methods, choose Tools | Templates.
		}

		@Override
		public void mouseReleased(MouseEvent e) {

		}

		@Override
		public void mouseEntered(MouseEvent e) {
			// throw new UnsupportedOperationException("Not supported yet."); //To change
			// body of generated methods, choose Tools | Templates.
		}

		@Override
		public void mouseExited(MouseEvent e) {
			// throw new UnsupportedOperationException("Not supported yet."); //To change
			// body of generated methods, choose Tools | Templates.
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabe2 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		jPanel1.setLayout(null);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jPanel1.add(jLabel1);
		jLabel1.setBounds(1060, 10, 80, 32);

		jLabe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/animatedghost.gif"))); // NOI18N
		jPanel1.add(jLabe2);
		jLabe2.setBounds(530, 330, 120, 120);

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halloweennew.jpg"))); // NOI18N
		jLabel2.setText("jLabel2");
		jPanel1.add(jLabel2);
		jLabel2.setBounds(0, 0, 1160, 650);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ShootingGame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ShootingGame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ShootingGame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ShootingGame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new ShootingGame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabe2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables
}